# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
        migrations.AddField(
            model_name='document',
            name='data',
            field=models.FileField(default=None, upload_to='documents'),
            preserve_default=False,
        ),
    ]
